### ISSUE TITLE
changeEditorInterface fails when used with editContentType

### ISSUE THREAD

**Issue by coffeepunk** [contentful/migration-cli#81]
If I create a new Content Model with a migration like the one below, then `changeEditorInterface` works and the migration goes through.

```
module.exports = function(migration) {
    const genricModel = migration.createContentType('genericModel', {
        name: 'Generic test model',
        description: 'Testing the migration API'
    });
    genricModel.createField('region', {
        name: 'Country',
        type: 'Symbol',
        required: true,
        validations: [{'in': ['SE', 'DK', 'NO']}]
    });
    genricModel.changeEditorInterface('region', 'radio');
};
```

But if I run this migration on an already existing Content Model, the actual field is created but the `changeEditorInterface` throws an error and the migration halts, but the field has been created with the default editor interface.

```
module.exports = function(migration) {
    const genricModel = migration.editContentType('genericModel');
    genricModel.createField('region', {
        name: 'Country',
        type: 'Symbol',
        required: true,
        validations: [{'in': ['SE', 'DK', 'NO']}]
    });
    genricModel.changeEditorInterface('region', 'radio');
};
```
The migration above givs this error

```
The following migration has been planned

Update Content Type genericModel

  Create field region
    - name: "Country"
    - type: "Symbol"
    - required: true
    - validations: [{"in":["SE","DK","NO"]}]

Publish Content Type genericModel
Update editor interface for Content Type genericModel
  - Field region: radio
? Do you want to apply the migration Yes
 ✔ Update Content Type genericModel
 ❯ Update editor interface for Content Type genericModel
   ✖ Making requests (1/1)
     → Batch failed
🚨  Migration unsuccessful
Batch failed

Error: {"status":"Conflict","message":"","details":{},"url":"https://api.contentful.com:443/spaces/space-id-anonymized/environments/master/content_types/genericModel/editor_interface"}
```
and produces the following log, I've removed project path and space id

```
VersionMismatch: {
  "status": 409,
  "statusText": "Conflict",
  "message": "",
  "details": {},
  "request": {
    "url": "https://api.contentful.com:443/spaces/space-id-anonymized/environments/master/content_types/genericModel/editor_interface",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/vnd.contentful.management.v1+json",
      "X-Contentful-User-Agent": "app contentful.migration-cli/0.6.0; sdk contentful-management.js/4.1.2; platform node.js/8.9.4; os macOS/17.4.0;",
      "Authorization": "Bearer ...e61aa",
      "user-agent": "node.js/v8.9.4",
      "Accept-Encoding": "gzip",
      "X-Contentful-Version": 15,
      "Content-Length": 144
    },
    "method": "put",
    "payloadData": "{\"controls\":[{\"fieldId\":\"title\",\"widgetId\":\"singleLine\"},{\"fieldId\":\"paragraph\",\"widgetId\":\"markdown\"},{\"fieldId\":\"region\",\"widgetId\":\"radio\"}]}"
  },
  "requestId": "f067c3e7f1013ce64ae867a5741fcf1f"
}
    at errorHandler (/project-path-anonymized/node_modules/contentful-management/dist/contentful-management.node.js:693:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
My workaround at the moment is to run the `createField` in one migration and then `changeEditorInterface` in a second.

**Comment by zcei** [comment]
Thanks for opening as a new issue 👍

As written in https://github.com/contentful/migration-cli/issues/57#issuecomment-372265906 I got it reproduced and aim for fixing it first and only then release the feature.

**Comment by Khaledgarbaya** [comment]
Fixed in https://github.com/contentful/migration-cli/pull/89
